services:
  mongodb:
    image: mongo:latest
    container_name: time_manager_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - timer_app_data:/data/db
    networks:
      - time_manager_network
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: time_manager_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://user:mongopass@mongodb:27017/time_management?authSource=admin
      JWT_SECRET: test_secret
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - time_manager_network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: time_manager_frontend
    restart: unless-stopped
    ports:
      - '80:3000'
      - '443:3000'
    depends_on:
      - backend
    networks:
      - time_manager_network

networks:
  time_manager_network:
    driver: bridge

volumes:
  timer_app_data:
