services:
  mongodb:
    image: mongo:latest
    container_name: time_manager_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    networks:
      - time_manager_network
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: time_manager_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - time_manager_network

  frontend:
    build: ./frontend
    container_name: time_manager_frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - time_manager_network

networks:
  time_manager_network:
    driver: bridge

volumes:
  mongo_data:
    external: true
    name: mongo_data
